apiVersion: v1
kind: Pod
metadata:
  name: curl-unmeshed
  namespace: simple-app
  labels:
    app: curl
  annotations:
    linkerd.io/inject: disabled
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-meshed
  namespace: simple-app
  labels:
    app: curl
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
