apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJMk1ERXlOREV3TVRBek9Gb1lEekl4TWpVeE1qTXhNVEF4TURNNFdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjhCS01JaFRuUGtsTGMrNEx3c2ZFSUp2dVI1ZHZDU1VyUW5ONGtWZmI5QkF4OHROMStZdXB0VE4yVHZNb0dZY3MKekJ2cjNub2Z3TmtzcEthTHFXZnNLKzFMdnkwVDZDNXFDU2JrSkliWVJ0bWJqajcxcm94Z0tEbWNFbnY2citEQwp5dFA4dnVQWUthUzNzeWpzOHlmR2VpTkxlaS9DZTk0YVpTb0ZpZHNJN3ptZlIxN0Z0WkpiTjBEam1Gc2Q0ZXQzCjQySkJwMkJxQkF6eTZGYmpNbm5qSTZiZ2FtWDA4aENXSjNMY1Y1R05TcWpiM3ZWMTVYdnFPYkQ1MEczbnF6T2sKQWl1OXBibjAyZlVWNUxJM2pLcFFkbE16WFRJY0YrbzFlcllOdllybjVEcTM4U01WNkpCSi8xTUcxaUFSdXNiagppZ3dhNUZGb1RmYXpiWFBzNFBOWU53SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVsWGQ3SlVSY0dHd2FGUzJ3YlRuZ2NxNUdsbmd3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFDVWNoeDdjQ1VMRUQwOVgvSGlPcUhZT3l2TmZlY2tIb1h4dkJjQy92OFEvbjJLYQpxbWRKVlA0VHMySlJnb1gzOE1oenRTZWZONDZCdGorYndtYjlhS20vUFFGWXFXYzVjaDFtVVc1RVRNWVJNbkFBCnZLc0ErRkNCdlhNR1JJUzMzNXhZbWt5WUUvb0gwMVlhYWlWaTZmOTVNN0Y1dG5MTkpxNjhWaktoYmFwTVV4RDQKWmN4THh5Wm5UMS9kL3JGdXBzQUxuZmh6UGJaM296VHJST2tFci95RC9yRkorUzJUcFo0azlmRHU0T0JKVFlMaApCc2l0bFF2UXIyaTBpTHFEVkFocjRvMXpQVWJXVkZpTzNKWkNrV2tkeDlrY0ZkUzBldE8xVVJ0bEgwaDNrVUNYClJTQkd2QTQ3WHhWcksva2tPYmNqOFNnVFF1dmhVTVU2eGI5a3JPMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://f3d00b17-6c81-42f7-a44c-aadcdf55e196.kr.vnks.ntruss.com
  name: nks_kr_devkorea-nks-1_f3d00b17-6c81-42f7-a44c-aadcdf55e196
contexts:
- context:
    cluster: nks_kr_devkorea-nks-1_f3d00b17-6c81-42f7-a44c-aadcdf55e196
    user: nks_kr_devkorea-nks-1_f3d00b17-6c81-42f7-a44c-aadcdf55e196
  name: devkorea-nks-1
current-context: devkorea-nks-1
kind: Config
users:
- name: nks_kr_devkorea-nks-1_f3d00b17-6c81-42f7-a44c-aadcdf55e196
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - --clusterUuid
      - f3d00b17-6c81-42f7-a44c-aadcdf55e196
      - --region
      - KR
      command: ncp-iam-authenticator
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
