apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJMk1ERXlOVEE1TURjeE5sb1lEekl4TWpZd01UQXhNRGt3TnpFMldqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjIxUHFwQ2k2OHFlVmZQd1NMdG4zdm1lTDBKM0pQWDkwTDlLdXRjTkJnRnpPTUU4REo5WTVYOEhvSFlKZlpLcEcKWW1DOEJmS3ZjckZOTE9lV0U0bitEN2l3cEcvQnNBOEwrdlhaVERZc1EyUUhWcGJGZEJibUJEeWxBU1pvOXoxTgpNSUtOVFdSRDljYnNiQ0czdDJuWTRsSnFNYlpObWlwMVlDMHY5Qm1sVTl0WWcrWDR5aUx1YWYzeCs0bFRrRjFJCkUzcy9zeWpyM0w2V0p0cmdGa2hKdFB4Sk5nTkszcHMxNnhvVVZRL0MyWjJQZFRHWGFjSGhIb0ZvNndRSk40dE0KejlvRW00SHMxakZVYWkzMUE0U09Za29XNkxDcmpiaTlGdTNRaFJXOFp1VXoxa2Y3RHU0cW5mS29uSGgxVnB2VgpycU1BZUN1dkZBZXBMZlBXOUludW53SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVuRm9LVnZJbkxZNUVkdkp3Z3NuSzVNcXAza293RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFDVERMcGc4Z3FnSjlSQ21sYVkyKzdvWWNyQ0QwUHpmOWVoYy9qZng4cWlMWFZFdQpQcUMyMHB4eHdZbFBBS2FXT1N6Z2VuZ1I1MUZZMngzcXFrL0lSZlVZTU1jeDRkakhHS092N3Z2d1NBQS9KWEsvCnZ5dnpUeFpLczdFN2FMdjdiQlMrSzdpYTBaNHNxWnFKQ1FpN0tUbDhTWGhQV21PL2Y2R2x6SDR6WHBLWTFGQ1kKcm02MVVHVTJQUHc2SVkwUTRUaGRyMTlIVGwyZjZIeWZMNkdDdFN6K1E3aGx2eE94TVlpdmtHRjFTT2ZTK3pscgoyenk4b003MmgwcERnODlRS1U2ejkwUW50ZUFGeFVQWVE2djI4WGhsdzR1N3FjMGh0aVdNNXEvOXpQcmU3TW9nCnFtM0F5RzRtTlNaV1JWRnBUcTRobHRqU01VOUtIZmJ1aWtGK2FRMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://e79af570-e190-4e20-a666-978e0bd0baa8.kr.vnks.ntruss.com
  name: nks_kr_devkorea-nks-1_e79af570-e190-4e20-a666-978e0bd0baa8
contexts:
- context:
    cluster: nks_kr_devkorea-nks-1_e79af570-e190-4e20-a666-978e0bd0baa8
    user: nks_kr_devkorea-nks-1_e79af570-e190-4e20-a666-978e0bd0baa8
  name: devkorea-nks-1
current-context: devkorea-nks-1
kind: Config
users:
- name: nks_kr_devkorea-nks-1_e79af570-e190-4e20-a666-978e0bd0baa8
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - --clusterUuid
      - e79af570-e190-4e20-a666-978e0bd0baa8
      - --region
      - KR
      command: ncp-iam-authenticator
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
