apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJMk1ERXlOREV3TVRBMU1Gb1lEekl4TWpVeE1qTXhNVEF4TURVd1dqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCm84NDhTaEpuUnRDWHV6RDNtSWJGc0xmdnhxS01tcVNWTjI3UjFma0g4bGx2WlRkVWVMSzFoUnRQMnlqQ1RMbDIKbit4Y0k5cThNRnlNS04xT1hvTnRnSmozYXFycUNXTGF4ZlloaWZPcU1MbUpWWUw3RGsyZlZmUFZuL1NEQWxEUAptRFRqYy9abTdpMHhtL0ROVmx3dlpWTUlIMnlzOUhidTZyUGhUTFhzNmtQMzFvQnRiUktXQVM1dkVWZ1BzdTdTCm02TkVWNmlHUTF1NUJoa05TeUNDVlZxKyt6Uy9uUmFtRVJIK2xIV0lPWmlHQVh2N05WTVBVZ2l0MXVsaUVpWVAKUFhSMlVwTVF5clFTQ3N6UzY4UmgzUVFOMXdwWUt1Rkc1T0JtWjFaTDlzV2NEcks2cE1vYUQzR1pRSk9rODdEKwpVdGp0M2EvRUZBNE5MTDdtNG1lRStRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUyZ1pNek9WNVlnRVJFbWZVTm1WbkN4c0pZd1F3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFEdEkzekpKLzZmVGFZb3k3bTkzaGs4QmtpUTh0Tjl4ZEhGN2hDejhYTE9GbVRrYwo4MVgvM1FOeXRqaThJRHp5QWdzNXZGbm9tZ2FCRjR3dWUyS2VWaTlCdUNTc2wzdG9OOVJpU2YraGppNVNiaXpECmxkVmJvMmRxOFBETnZ2TjByY25qblVBc250M3JaZ1NRbm8zN1VacjJlMmJibWNuUG5DKzg1WkZhSjdqck1Td1kKMXFVZmRrZ3NiOHhFZzFyeDZ3MUI5Y3NodGVBMjMxNFZhc1h5SE5teGdwcWk2NE5odXBHQ2YzSjRyVmx4UTE2dQpZVGswUnZXVzJLVlBXS2NzSXRwR2h4YTJlU1NxaE9JTEgzSDhtaE9LTW9aRlVEZzB0M0FSR21kV1lrajg0MGs1CmJXbmVhZHpVYy9FSGZ0dlR1ZnI4UDh4bklHM25PR3BzY2FtREd2WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://52329cf9-905d-4162-8fad-7a8a6126c796.kr.vnks.ntruss.com
  name: nks_kr_devkorea-nks-2_52329cf9-905d-4162-8fad-7a8a6126c796
contexts:
- context:
    cluster: nks_kr_devkorea-nks-2_52329cf9-905d-4162-8fad-7a8a6126c796
    user: nks_kr_devkorea-nks-2_52329cf9-905d-4162-8fad-7a8a6126c796
  name: devkorea-nks-2
current-context: devkorea-nks-2
kind: Config
users:
- name: nks_kr_devkorea-nks-2_52329cf9-905d-4162-8fad-7a8a6126c796
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - --clusterUuid
      - 52329cf9-905d-4162-8fad-7a8a6126c796
      - --region
      - KR
      command: ncp-iam-authenticator
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
